### ISSUE TITLE
Unknown property 'project' while trying to use extraMappings

### ISSUE THREAD

**Issue by IzzelAliz** [SpongePowered/MixinGradle#16]
The build.gradle script is
```
mixin {
    add sourceSets.main, 'mixins.some.refmap.json'
    extraMappings('extra_mapping.tsrg')
}
```

and get following error

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':arclight-forge-1.14:compileJava'. <32 internal calls>
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'project' for object of type org.spongepowered.asm.gradle.plugins.MixinExtension. <2 internal calls>
	at org.spongepowered.asm.gradle.plugins.MixinExtension_Decorated.getProperty(Unknown Source)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_applyCompilerArgs_closure16.doCall(MixinExtension.groovy:591)
	at org.spongepowered.asm.gradle.plugins.MixinExtension.applyCompilerArgs(MixinExtension.groovy:591)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_configure_closure12.doCall(MixinExtension.groovy:499) <10 internal calls>
	... 31 more
```

**Comment by gabizou** [comment]
I can say that this is affecting a mixed bag of people working on SpongeCommon now with Gradle 5.6.2

Relevant [stack trace](https://gist.github.com/gabizou/1d5770fcf7ae38d4e5f07a17bf8be38a) and [relevant script that fails](https://github.com/SpongePowered/SpongeCommon/blob/78eaf263e84e5b32b3bf21193d96b394173dcb42/build.gradle.kts#L260-L264) (granted, we're using kotlin-dsl, but this property intermittently fails).

This is the setup:
MixinGradle 0.7-SNAPSHOT
Gradle 5.6.4
ForgeGradle 3.0.184

The awkward aspect of all of this is that this was failing for me locally, until I did some quasi clean and break and *somehow* my workspace is functioning, but @Zidane and some others at Sponge aren't able to get the same workspace working anymore.

@Mumfrey if you're up for it, I'd be more than happy at updating the extension to using Gradle's [properties api](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html) introduced in 4.3 (and an example written in a build script [with a task](https://github.com/SpongePowered/SpongeCommon/blob/b6cd9f597552efc422583bf7a476f1908b32e573/build.gradle.kts#L766-L772))
