### ISSUE TITLE
Compatibility with ForgeGradle 5 remapJar Task

### ISSUE THREAD

**Issue by shartte** [SpongePowered/MixinGradle#29]
I am running the latest snapshot of MixinGradle, together with the latest ForgeGradle 5 on J16 and Gradle 7.1, and I am running into this exception when building my project:

```
Execution failed for task ':reobfJar'.
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method extraMapping() for arguments [D:\ae2-forge\build\tmp\compileJava\compileJava-mappings.tsrg] on task ':reobfJar' of type net.minecraftforge.gradle.userdev.tasks.RenameJarInPlace.
	at org.gradle.internal.metaobject.AbstractDynamicObject$CustomMissingMethodExecutionFailed.<init>(AbstractDynamicObject.java:190)
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:184)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:167)
	at net.minecraftforge.gradle.userdev.tasks.RenameJarInPlace_Decorated.invokeMethod(Unknown Source)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_configure_closure17$_closure27.doCall(MixinExtension.groovy:770)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.doExecute(AbstractTask.java:699)
```

This was probably caused by ForgeGradle moving to Gradle properties in this commit:
https://github.com/MinecraftForge/ForgeGradle/commit/6b322d40d359dff0299010664189d1fec85ba544#diff-bd94873d0808b53df6cb08cbe7d1cb4f2aa4668668438b1e6df8b3a22937dd1aR83

**Comment by SizableShrimp** [comment]
This issue can be closed as it has been fixed.
